/**
 * Hulk Integration Service Api
 * Hulk Integration Service Api
 *
 * OpenAPI spec version: 2.0.0
 * Contact: api-support@sunrise.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Choice Question Form
 */
export interface ChoiceQuestionForm extends models.QuestionForm {
    choiceQuestionFormType?: string;

    options?: Array<models.Option>;

}
